name: front
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'



dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  auto_size_text: ^3.0.0
  badges: ^3.1.1
  eva_icons_flutter: ^3.1.0
  page_transition: ^2.0.9
  cached_network_image: ^3.2.3
  size_config: ^2.0.3
  editable_image: ^2.0.0
  date_picker_timeline: ^1.2.5
  easy_date_timeline: ^0.0.7
  dio: ^5.3.2
  raised_buttons: ^0.0.2
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  syncfusion_flutter_datepicker: ^22.2.12
  shared_preferences: ^2.2.1
  settings_ui: ^2.0.2
  awesome_dialog: ^3.1.0
  rating_dialog: ^2.0.4
  email_validator: '^2.1.16'
  intl: ^0.18.1
  overlay_group_avatar: ^0.0.4
  flutter_image_stack: ^0.0.7
  bottom_picker: ^2.1.0
  flutter_login: ^4.2.1
  fl_chart: ^0.63.0
  image_picker: ^1.0.4
  cloudinary: ^1.2.0
  dropdown_button2: ^2.3.9
  path: ^1.8.3
  loading_indicator: ^3.1.1
  cloudinary_dart: ^0.0.11
  cloudinary_flutter: ^1.0.0
  http: ^1.1.0
  chat_bubbles: ^1.5.0
  audioplayers: ^5.2.0
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages